/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiVoiceQaRouteImport } from './routes/api/voice-qa'
import { Route as ApiTtsProxyRouteImport } from './routes/api/tts-proxy'

const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceQaRoute = ApiVoiceQaRouteImport.update({
  id: '/api/voice-qa',
  path: '/api/voice-qa',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsProxyRoute = ApiTtsProxyRouteImport.update({
  id: '/api/tts-proxy',
  path: '/api/tts-proxy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/preferences': typeof PreferencesRoute
  '/scan': typeof ScanRoute
  '/api/tts-proxy': typeof ApiTtsProxyRoute
  '/api/voice-qa': typeof ApiVoiceQaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/preferences': typeof PreferencesRoute
  '/scan': typeof ScanRoute
  '/api/tts-proxy': typeof ApiTtsProxyRoute
  '/api/voice-qa': typeof ApiVoiceQaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/preferences': typeof PreferencesRoute
  '/scan': typeof ScanRoute
  '/api/tts-proxy': typeof ApiTtsProxyRoute
  '/api/voice-qa': typeof ApiVoiceQaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/preferences'
    | '/scan'
    | '/api/tts-proxy'
    | '/api/voice-qa'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/preferences'
    | '/scan'
    | '/api/tts-proxy'
    | '/api/voice-qa'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/preferences'
    | '/scan'
    | '/api/tts-proxy'
    | '/api/voice-qa'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  PreferencesRoute: typeof PreferencesRoute
  ScanRoute: typeof ScanRoute
  ApiTtsProxyRoute: typeof ApiTtsProxyRoute
  ApiVoiceQaRoute: typeof ApiVoiceQaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice-qa': {
      id: '/api/voice-qa'
      path: '/api/voice-qa'
      fullPath: '/api/voice-qa'
      preLoaderRoute: typeof ApiVoiceQaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts-proxy': {
      id: '/api/tts-proxy'
      path: '/api/tts-proxy'
      fullPath: '/api/tts-proxy'
      preLoaderRoute: typeof ApiTtsProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  PreferencesRoute: PreferencesRoute,
  ScanRoute: ScanRoute,
  ApiTtsProxyRoute: ApiTtsProxyRoute,
  ApiVoiceQaRoute: ApiVoiceQaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
